# ========================
#   BASE DE DATOS RDS
# ========================
spring.datasource.url=jdbc:postgresql://panaderia-db.co94osygkh2d.us-east-1.rds.amazonaws.com:5432/panaderia_db
spring.datasource.username=dbmaster
spring.datasource.password=Admin1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
#   JPA / HIBERNATE
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=public

# ========================
#   PERFIL
# ========================
spring.profiles.active=prod
server.port=8080



